apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/containers/ramalama?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: >-
      event == "push" && target_branch == "main"
  labels:
    appstudio.openshift.io/application: ramalama
    appstudio.openshift.io/component: rocm-rag
    pipelines.appstudio.openshift.io/type: build
  name: rocm-rag-on-push
  namespace: ramalama-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ramalama-tenant/rocm-rag:{{revision}}
  - name: build-platforms
    value:
    - linux-d160-c8xlarge/amd64
  - name: dockerfile
    value: container-images/common/Containerfile.rag
  - name: build-args
    value:
    - TORCH_BACKEND=rocm6.3
  pipelineRef:
    name: push-pipeline
  timeouts:
    pipeline: 12h
    finally: 15m
  taskRunTemplate:
    serviceAccountName: build-pipeline-rocm-rag
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
