[pytest]
testpaths = test
markers =
    e2e
    distro_integration
    slow: tests that take more than ~30 seconds, usually running an inference server
addopts = -m 'not e2e and not slow' --color=yes --durations=10
