FROM quay.io/fedora/fedora:43

COPY --chmod=755 container-images/stable-diffusion/entrypoint.sh /usr/bin/entrypoint.sh
COPY container-images/scripts/build_stable_diffusion.sh /src/

WORKDIR /src/
RUN ./build_stable_diffusion.sh
WORKDIR /

ENTRYPOINT ["/usr/bin/entrypoint.sh"]
CMD ["sd"]
