[containers]
# netns="host"
# userns="host"
# ipcns="host"
# utsns="host"
# cgroups="enabled"
# cgroupns="host"
# pidns="host"
log_driver = "k8s-file"

[engine]
# cgroup_manager = "cgroupfs"
events_logger="file"
