FROM podman-llm

RUN llama-cpp-main --hf-repo TheBloke/Mistral-7B-Instruct-v0.1-GGUF -m mistral-7b-instruct-v0.1.Q2_K.gguf

ENTRYPOINT ["llama-cpp-main-wrapper", "-m", "/mistral-7b-instruct-v0.1.Q2_K.gguf"]
CMD ["--instruct"]
