FROM podman-llm/podman-llm:41

RUN llama-cpp-main --hf-repo TheBloke/Mistral-7B-Instruct-v0.1-GGUF -m mistral-7b-instruct-v0.1.Q2_K.gguf

ENTRYPOINT ["llama-cpp-main", "-m", "/mistral-7b-instruct-v0.1.Q2_K.gguf", "--log-disable"]
CMD ["--instruct"]
