ARG PARENT=quay.io/ramalama/ramalama:latest
FROM $PARENT

ENV UV_PYTHON_INSTALL_DIR="/opt/uv/python"

ENV UV_HTTP_TIMEOUT=500

ENV UV_INDEX_STRATEGY="unsafe-best-match"
ENV UV_LINK_MODE="copy"

COPY . /src/ramalama
WORKDIR /src/ramalama
RUN container-images/scripts/build-vllm.sh "ramalama"
WORKDIR /

