#!/usr/bin/env python3

import argparse
import sys


def main(args):
    sys.path.append('./')
    from ramalama.common import exec_cmd

    exec_cmd(args)

    return 0


if __name__ == "__main__":
    main(sys.argv[1:])
