apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/containers/ramalama?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: >-
      event == "push" && target_branch == "main"
  labels:
    appstudio.openshift.io/application: ramalama
    appstudio.openshift.io/component: ramalama
    pipelines.appstudio.openshift.io/type: build
  name: ramalama-on-push
  namespace: ramalama-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ramalama-tenant/ramalama:{{revision}}
  - name: build-platforms
    value:
    - linux-c4xlarge/amd64
    - linux-c4xlarge/arm64
  - name: dockerfile
    value: container-images/ramalama/Containerfile
  - name: test-image
    value: quay.io/redhat-user-workloads/ramalama-tenant/bats:{{revision}}
  - name: test-envs
    value:
    - RAMALAMA_IMAGE=quay.io/redhat-user-workloads/ramalama-tenant/ramalama:{{revision}}
  - name: test-commands
    value:
    - make validate
    - make unit-tests
    - make cov-tests
  pipelineRef:
    name: push-pipeline
  timeouts:
    pipeline: 6h
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
