FROM fedora:41

RUN dnf install -y rocminfo rocm-opencl rocm-clinfo rocm-hip git jq procps-ng vim clblast-devel 'dnf5-command(builddep)' && dnf builddep -y llama-cpp

ENV LLAMA_CLBLAST=1
ENV LLAMA_CURL=1
ENV LLAMA_HIPBLAS=1
ENV LLAMA_VULKAN=1

RUN git clone https://github.com/ggerganov/llama.cpp.git && cd llama.cpp && git reset --hard 5921b8f089d3b7bda86aac5a66825df6a6c10603 && make -j $(nproc)
RUN cd llama.cpp && for file in *; do if [ -f "$file" ] && [ -x "$file" ]; then mv "$file" /usr/bin/llama-cpp-"$file"; fi; done
COPY podman-llm-shell /usr/bin

