FROM podman-llm

RUN llama-cpp-main --hf-repo ibm-granite/granite-3b-code-instruct-GGUF -m granite-3b-code-instruct.Q4_K_M.gguf

ENTRYPOINT ["podman-llm-shell", "granite-3b-code-instruct.Q4_K_M.gguf"]

