# Base image with CANN for compilation
ARG ASCEND_VERSION=cann:8.0.0-910b-openeuler22.03-py3.10

FROM quay.io/ascend/${ASCEND_VERSION} AS builder
ARG GOLANG_VERSION
COPY container-images/scripts/build_llama.sh \
     container-images/scripts/lib.sh \
     /src/
WORKDIR /src/
RUN ./build_llama.sh cann

FROM quay.io/ascend/${ASCEND_VERSION}
RUN --mount=type=bind,from=builder,source=/tmp/install,target=/tmp/install \
    cp -a /tmp/install/bin/ /usr/ && \
    cp -a /tmp/install/lib64/*.so* /usr/lib64/
ENTRYPOINT [ \
    "/bin/bash", \
    "-c", \
    "export LD_LIBRARY_PATH=/usr/lib:${LD_LIBRARY_PATH} && source /usr/local/Ascend/ascend-toolkit/set_env.sh && exec \"$@\"", "--" \
]
