#!/usr/bin/env python3

import cmd

class RamaLamaShell(cmd.Cmd):
    prompt = "> "

    def do_EOF(self, line):
        print("")
        return True

    def default(self, line):
        if line == "/bye":
            return True

        print(line)

if __name__ == '__main__':
    try:
        RamaLamaShell().cmdloop()
    except KeyboardInterrupt:
        print("")

