#!/usr/bin/env python3

import argparse
import cmd
import itertools
import json
import os
import sys
import time
import urllib.error
import urllib.request


def construct_request_data(conversation_history):
    data = {
        "stream": True,
        "messages": conversation_history,
    }

    return data


def should_colorize():
    t = os.getenv("TERM")
    return t and t != "dumb" and sys.stdout.isatty()


def res(response, color):
    color_default = ""
    color_yellow = ""
    if (color == "auto" and should_colorize()) or color == "always":
        color_default = "\033[0m"
        color_yellow = "\033[33m"

    print("\r", end="")
    assistant_response = ""
    for line in response:
        line = line.decode("utf-8").strip()
        if line.startswith("data: {"):
            line = line[len("data: ") :]
            choice = json.loads(line)["choices"][0]["delta"]
            if "content" in choice:
                choice = choice["content"]
            else:
                continue

            print(f"{color_yellow}{choice}{color_default}", end="", flush=True)
            assistant_response += choice

    print("")
    return assistant_response


def req(conversation_history, url, color):
    data = construct_request_data(conversation_history)
    json_data = json.dumps(data).encode("utf-8")
    headers = {
        "Content-Type": "application/json",
    }

    # Create a request
    request = urllib.request.Request(url, data=json_data, headers=headers, method="POST")

    # Send request
    i = 0.01
    for c in itertools.cycle(['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏']):
        if i > 10:
            break

        try:
            response = urllib.request.urlopen(request)
            break
        except Exception:
            print(f"\r{c}", end="", flush=True)
            time.sleep(i)
            i *= 2

    return res(response, color)


class RamaLamaShell(cmd.Cmd):
    def __init__(self, parsed_args):
        super().__init__()
        self.conversation_history = []
        self.parsed_args = parsed_args
        self.prompt = parsed_args.prefix
        self.url = f"{parsed_args.host}/v1/chat/completions"

    def do_EOF(self, user_content):
        print("")
        return True

    def default(self, user_content):
        if user_content == "/bye":
            return True

        self.conversation_history.append({"role": "user", "content": user_content})
        self.conversation_history.append(
            {"role": "assistant", "content": req(self.conversation_history, self.url, self.parsed_args.color)}
        )


def main(args):
    parser = argparse.ArgumentParser(description="Run ramalama client")
    parser.add_argument(
        '--color',
        '--colour',
        default="auto",
        choices=['never', 'always', 'auto'],
        help='possible values are "never", "always" and "auto".',
    )
    parser.add_argument("--prefix", type=str, default="> ", help="prefix for the user prompt")
    parser.add_argument(
        "host", type=str, nargs="?", default="http://127.0.0.1:8080", help="the host to send requests to"
    )
    parsed_args = parser.parse_args(args)

    try:
        RamaLamaShell(parsed_args).cmdloop()
    except KeyboardInterrupt:
        print("")


if __name__ == '__main__':
    main(sys.argv[1:])
