#!/usr/bin/env python3

import os
import sys


def main(args):
    sys.path.append('./')
    os.environ["PATH"] += f"{os.pathsep}libexec"
    from ramalama.common import exec_cmd

    pid = os.fork()
    if pid == 0:
        cmd = ["ramalama-serve-core"]
        exec_cmd(cmd, stderr2null=True)
        return 0

    cmd = ["ramalama-client-core"]
    exec_cmd(cmd)


if __name__ == '__main__':
    main(sys.argv[1:])
