FROM quay.io/fedora/fedora:42 as builder

COPY container-images/intel-gpu/oneAPI.repo /etc/yum.repos.d/
COPY . /src/ramalama
WORKDIR /src/ramalama
RUN container-images/scripts/build_llama_and_whisper.sh intel-gpu

FROM quay.io/fedora/fedora:42

COPY --from=builder /tmp/install/ /usr/
COPY container-images/intel-gpu/oneAPI.repo /etc/yum.repos.d/

RUN dnf install -y procps-ng intel-oneapi-runtime-mkl intel-oneapi-mkl-sycl-dft \
      intel-level-zero oneapi-level-zero intel-compute-runtime libcurl lspci \
      clinfo intel-oneapi-runtime-compilers intel-oneapi-mkl-core \
      intel-oneapi-mkl-sycl-blas intel-oneapi-runtime-dnnl gawk && \
    chown 0:0 /etc/passwd && \
    chown 0:0 /etc/group && \
    chmod g=u /etc/passwd /etc/group /home

COPY --chmod=755 container-images/intel-gpu/entrypoint.sh /usr/bin

ENTRYPOINT ["/usr/bin/entrypoint.sh"]
