FROM quay.io/fedora/fedora:43 as builder

COPY intel-gpu/oneAPI.repo /etc/yum.repos.d/
COPY scripts/build_llama_and_whisper.sh /

RUN chmod +x /build_llama_and_whisper.sh ; \
    /build_llama_and_whisper.sh intel-gpu

FROM quay.io/fedora/fedora:43

COPY --from=builder /tmp/install/ /usr/
COPY intel-gpu/oneAPI.repo /etc/yum.repos.d/
COPY --chown=0:0 intel-gpu/entrypoint.sh /

RUN dnf install -y procps-ng python3 python3-pip python3-devel intel-level-zero oneapi-level-zero intel-compute-runtime libcurl lspci clinfo intel-oneapi-runtime-compilers intel-oneapi-mkl-core intel-oneapi-mkl-sycl-blas intel-oneapi-runtime-dnnl ; \
    chown 0:0 /etc/passwd ; \
    chown 0:0 /etc/group ; \
    chmod g=u /etc/passwd /etc/group /home ; \
    chmod +x /entrypoint.sh

USER 10000

ENTRYPOINT ["/entrypoint.sh"]
CMD [ "tail", "-f", "/dev/null" ]