FROM quay.io/ramalama/ramalama:latest

COPY ../scripts /scripts
RUN chmod +x /scripts/*.sh && \
    /scripts/build_llama_and_whisper.sh "$LLAMA_CPP_SHA" "$WHISPER_CPP_SHA" \
      "/usr" "-DGGML_VULKAN=1"

