FROM registry.fedoraproject.org/fedora:43

COPY ../scripts /scripts
RUN chmod +x /scripts/*.sh && \
    /scripts/build_llama_and_whisper.sh "rocm" 

ENV WHISPER_CPP_SHA=${WHISPER_CPP_SHA}
ENV LLAMA_CPP_SHA=${LLAMA_CPP_SHA}
