FROM fedora:39

RUN mkdir -p /models
RUN dnf install -y git jq procps-ng vim clblast-devel vulkan-headers \
      vulkan-loader-devel glslc glslang python3-pip dnf-plugins-core \
      python3-dnf-plugin-versionlock cmake gcc-c++ libcurl-devel && \
    if [ "$(uname -m)" = "aarch64" ]; then \
      dnf copr enable -y slp/mesa-krunkit && \
      dnf install -y mesa-libOpenCL-23.3.5-102.aarch64 \
        mesa-vulkan-drivers-23.3.5-102.aarch64 && \
      dnf versionlock mesa-libOpenCL-23.3.5-102.aarch64 \
        mesa-vulkan-drivers-23.3.5-102.aarch64; \
    fi && \
    dnf install -y vulkan-tools && \
    dnf clean all && \
    rm -rf /var/cache/*dnf*

RUN pip install -U "huggingface_hub[cli]"

ENV LLAMA_CCACHE=0
ENV LLAMA_CURL=1
ENV LLAMA_VULKAN=1

RUN git clone -b podman-llm https://github.com/ericcurtin/llama.cpp.git && \
    cd llama.cpp && \
    cmake -B build -DLLAMA_CCACHE=0 -DLLAMA_VULKAN=1 -DLLAMA_CURL=1 && \
    cmake --build build --config Release -j $(nproc) && \
    cd build/bin && \
    for file in *; do \
      if [ -f "$file" ] && [ -x "$file" ]; then \
        echo "$file" && \
        mv "$file" /usr/bin/llama-"$file"; \
      fi; \
    done; \
    cd / && \
    rm -rf llama.cpp
