FROM registry.access.redhat.com/ubi9/ubi:9.5-1745848351

COPY rocm-ubi/amdgpu.repo /etc/yum.repos.d/
COPY rocm-ubi/rocm.repo /etc/yum.repos.d/
COPY --chmod=755 ../scripts /usr/bin

ARG AMDGPU_TARGETS=
ENV AMDGPU_TARGETS=${AMDGPU_TARGETS}
RUN build_llama_and_whisper.sh "rocm"
