FROM registry.access.redhat.com/ubi9/ubi:9.5-1744101466

COPY rocm/amdgpu.repo /etc/yum.repos.d/
COPY rocm/rocm.repo /etc/yum.repos.d/
COPY --chmod=755 ../scripts /usr/bin

ARG AMDGPU_TARGETS=
ENV AMDGPU_TARGETS=${AMDGPU_TARGETS}
RUN build_llama_and_whisper.sh "rocm"
