ARG PARENT=quay.io/fedora/fedora:44
FROM $PARENT

ARG TORCH_BACKEND=cpu

ENV VIRTUAL_ENV="/opt/venv" \
    PATH="/opt/venv/bin:$PATH" \
    UV_NO_CACHE=1 \
    UV_NO_MANAGED_PYTHON=1 \
    UV_TORCH_BACKEND=$TORCH_BACKEND

RUN --mount=type=bind,target=/src,relabel=private \
    /src/container-images/scripts/build_tools.sh $TORCH_BACKEND
