FROM quay.io/fedora/fedora:43

ARG RAMALAMA_STACK_VERSION=0.2.6

RUN dnf -y install uv gcc python3-devel && \
    dnf -y clean all

RUN uv venv && \
    uv pip install ramalama_stack==${RAMALAMA_STACK_VERSION}

COPY --chmod=755 container-images/llama-stack/entrypoint.sh /usr/bin/entrypoint.sh

ENTRYPOINT [ "/usr/bin/entrypoint.sh" ]

CMD [ "llama",  "stack",  "run", "/root/.llama/distributions/ramalama/ramalama-run.yaml" ]
