FROM registry.fedoraproject.org/fedora:42

# hack that should be removed when the following PRs are merged
# https://github.com/containers/ramalama-stack/pull/37
# https://github.com/meta-llama/llama-stack/pull/2049
RUN wget -x ~/.llama/providers.d/remote/inference/ramalama.yaml https://raw.githubusercontent.com/containers/ramalama-stack/refs/heads/main/providers.d/remote/inference/ramalama.yaml && \
    wget -x ~/.llama/distributions/ramalama/ramalama-run.yaml https://raw.githubusercontent.com/containers/ramalama-stack/refs/heads/main/run.yaml

RUN dnf -y update && \
    dnf -y install uv cmake gcc gcc-c++ python3-devel pkg-config sentencepiece-devel && \
    uv pip install ramalama-stack && \
    uv run --with llama stack run ~/.llama/distributions/ramalama/ramalama-run.yaml --image-type venv --image-name /venv && \
    dnf -y clean all

COPY --chmod=755 llama-stack/entrypoint.sh /usr/bin/entrypoint.sh

ENTRYPOINT [ "/usr/bin/entrypoint.sh" ]

